### ISSUE TITLE
Cannot resolve symbol 'log'

### ISSUE THREAD

**Issue by alatriste-lee** [kanwangzjm/funiture#1]
~funiture-master\src\main\java\com\app\mvc\business\controller\FileController.java文件下，log没有被解析出来，请问是不是有哪个地方遗漏了？

Cannot resolve symbol 'log'

多谢。

**Comment by kanwangzjm** [comment]
log is from @Slf4j, maybe you should check if your idea has supported Lombok

**Comment by alatriste-lee** [comment]
感谢！

如http://my.oschina.net/baishi/blog/515346所说，是 Lombok插件没有安装，安装 Lombok 插件，重启Intellij idea 问题解决
