### ISSUE TITLE
编译不通过，无法运行

### ISSUE THREAD

**Issue by zzvv** [kanwangzjm/funiture#11]
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /Users/xx/Documents/apache-maven-3.3.9
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

IDEA内没错误，执行`` mvn clean && mvn install -Dmaven.test.skip=true `` 报错
/funiture/src/main/java/com/app/mvc/captcha/CaptchaService.java:[30,45] 错误: 找不到符号
在IDEA中单独编译``CaptchaService.java`` 
Error:(3, 29) java: 程序包com.app.mvc.acl.enums不存在

**Comment by zzvv** [comment]
> [ERROR] Failed to execute goal on project funiture: Could not resolve dependencies for project com.app:funiture:war:1.0.0: The following artifacts could not be resolved: com.sun.jdmk:jmxtools:jar:1.2.1, com.sun.jmx:jmxri:jar:1.2.1: Could not transfer artifact com.sun.jdmk:jmxtools:jar:1.2.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory: Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout legacy -> [Help 1]

不知道是什么包有引用这2个sun的私有外部包。

**Comment by kanwangzjm** [comment]
1、看错误应该是项目缺少lombok插件导致
2、之前是使用的zookeeper jar依赖这个jar，12月初的提交里移除了这个包，最新代码应该是不需要的
