### ISSUE TITLE
原理无法追踪

### ISSUE THREAD

**Issue by klaus20141002** [kanwangzjm/funiture#13]
/**
 * Created by jimin on 15/11/3.
 */
@Target({ ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Component
public @interface DBRepository {

    String value() default "";
}

很多地方的DAO直接使用

@DBRepository
public interface SysRoleUserDao {

    List<Integer> getUserIdListByRoleId(@Param("roleId") int roleId);

    List<Integer> getRoleIdListByUserId(@Param("userId") int userId);

    void deleteByRoleId(@Param("roleId") int roleId);

    void batchInsert(@Param("list") List<SysRoleUser> list);

    int countByRoleId(@Param("roleId") int roleId);
}

比如void batchInsert(@Param("list") List<SysRoleUser> list);
根据代码根本无法追踪实现逻辑？不知道这个地方测试是否用过？为什么可以这样

**Comment by kanwangzjm** [comment]
在applicationContext.xml里有这么一段配置
```
<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="annotationClass" value="com.app.mvc.common.DBRepository"/>
        <property name="basePackage" value="com.app.mvc"/>
    </bean>
```
只是为了让mybatis能扫描指定包路径下用这个注解定义的类。
这个适合dao分开放置的情况
