### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by shipengyan** [kanwangzjm/funiture#14]
![qq 20170117112619](https://cloud.githubusercontent.com/assets/1212932/22006644/cd5bcaea-dca7-11e6-9d56-eb05964cfc33.png)

上传后看下哦，不然没法看源码

**Comment by shipengyan** [comment]
![qq 20170117165822](https://cloud.githubusercontent.com/assets/1212932/22013894/3c2902ac-dcd6-11e6-81b7-28981a48f056.png)

**Comment by kanwangzjm** [comment]
感谢提醒，那是我本地ide的问题

**Comment by shipengyan** [comment]
@kanwangzjm 更新一下？
