### ISSUE TITLE
很有教课意义的项目

### ISSUE THREAD

**Issue by yuzhenguo27833** [kanwangzjm/funiture#19]
课程还仅仅只是你这个项目里面的一小部分，还有另外的一大部分是什么？ 我看Readme里面也没有说明，还有对应的前段jsp文件是什么，好像也没有~求大神解惑其他的部分实现的是什么功能。

**Comment by yuzhenguo27833** [comment]
感觉权限管理只是一小部分，其他部分有没有对应的前段？

**Comment by kanwangzjm** [comment]
你好，java开发企业级权限管理课程讲了很多通用的东西，其实这个项目也是从权限管理开始的一点点扩展起来的。目前正在出《多线程并发编程与多线程解决方案》的课程，是对java编程的一个进阶

**Comment by yuzhenguo27833** [comment]
谢谢大神解惑，请问这个课程大约什么时候出？ 很期待。

**Comment by kanwangzjm** [comment]
3月14日，马上了~ 当天中午应该能放出来，中午没放出来，下午也肯定能出来，如果购买的话，记得进qq学习群哦，我每天都会在群里答疑~ 现在这个课程也是

**Comment by yuzhenguo27833** [comment]
嗯嗯~ 我在这个框架下，尝试在ExampleScheduledJob这个类中引入Service，发现@Resource没法自动注入，请问如何解决？

**Comment by kanwangzjm** [comment]
使用ApplicationContextHelper
