### ISSUE TITLE
如何运行起项目？

### ISSUE THREAD

**Issue by ZhongXiaoBei** [kanwangzjm/funiture#2]
你好，我刚接触java web刚学完ssh，想找个项目学习，但是看这个项目好像不是myeclipse开发，不知如何部署运行，能否写个简要的说明？

**Comment by kanwangzjm** [comment]
我使用Intellij IDEA （ 含lombok插件）开发的，只依赖普通的tomcat、maven、mysql（sql在代码里）
使用git clone拿到代码后，在IDEA里open项目里的pom.xml，系统构建完，运行tomcat就可以了~

**Comment by ZhongXiaoBei** [comment]
好的，谢谢！
是现在主流的web开发已经不用myeclipse了吗？

**Comment by kanwangzjm** [comment]
个人感觉IDEA比myeclipse强大多了，工作中也是基本都用IDEA
