### ISSUE TITLE
整合redis 异常

### ISSUE THREAD

**Issue by coder-PengWenHao** [kanwangzjm/funiture#20]
项目整合redis的异常错误

![qq 20180826021915](https://user-images.githubusercontent.com/17332727/44621312-98832780-a8d6-11e8-9829-e983c3be3b5b.png)

![qq 20180826021931](https://user-images.githubusercontent.com/17332727/44621313-991bbe00-a8d6-11e8-885e-2e6bdb0f57d0.png)

**Comment by kanwangzjm** [comment]
dev环境的配置要做成resources root啊

**Comment by kanwangzjm** [comment]
在项目必看那一栏里我有注明啊
