### ISSUE TITLE
maven公共库缺少jar包

### ISSUE THREAD

**Issue by tour1986** [kanwangzjm/funiture#4]
Failed to execute goal on project funiture: Could not resolve dependencies for project com.app:funiture:war:1.0.0: The following artifacts could not be resolved: javax.jms:jms:jar:1.1, com.sun.jdmk:jmxtools:jar:1.2.1, com.sun.jmx:jmxri:jar:1.2.1: Could not transfer artifact javax.jms:jms:jar:1.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory: Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout legacy -> [Help 1]

 maven公共库缺少了jms jmxtool jmxri   我的解决方案是 下载了http://download.csdn.net/detail/tour1986/9610176 的jmxtool jmxri  
http://download.csdn.net/detail/zhao_sh/1384138 的jms
并安装：
mvn install:install-file -DgroupId=com.sun.jdmk -DartifactId=jmxtools -Dversion=1.2.1 -Dpackaging=jar -Dfile=D:\Downloads\funiture-master\jmxtools-1.2.1.jar -DgeneratePom=true -DcreateChecksum=true

mvn install:install-file -DgroupId=com.sun.jmx -DartifactId=jmxri -Dversion=1.2.1 -Dpackaging=jar -Dfile=D:\Downloads\funiture-master\jmxri-1.2.1.jar -DgeneratePom=true -DcreateChecksum=true

mvn install:install-file -DgroupId=javax.jms -DartifactId=jms -Dversion=1.1 -Dpackaging=jar -Dfile=D:\Downloads\funiture-master\jms-1.1.jar -DgeneratePom=true -DcreateChecksum=true

**Comment by kanwangzjm** [comment]
是否是你本地什么配置影响了这里，我这里不需要这些jar就可以运行；同时代码里也没有使用到这些jar里的类
