### ISSUE TITLE
在mac上部署的问题

### ISSUE THREAD

**Issue by audeSt** [kanwangzjm/funiture#7]
请问是需要先下载好mysql,redis,rabbitmq
然后在配置文件中修改用户名和密码吗?

然后build,把war包放在tomcat里面是吗?

**Comment by kanwangzjm** [comment]
必须的是mysql，jdk，tomcat
redis，rabbitmq不是强依赖的，代码里是注释的，打开配置才会用到他们
war放在tomcat里可以，不过可以直接启动
