### ISSUE TITLE
关于jdbc.properties 无法获取资源问题

### ISSUE THREAD

**Issue by tao0111225** [kanwangzjm/funiture#9]
作者你好
我在启动funiture 项目的时候 报了一个  not  found master.jdbc.url 的error。
我有尝试在javaRoot目录下创建一个，但是还是出现相同问题。

我有一个笨笨的解决方法：
就是硬编码jdbc的属性

**Comment by kanwangzjm** [comment]
readme 里有对这个做说明，在 其他[必看] 里
简单的说，就是将resource.dev或resource.prod中一个文件夹也和resources作成source root
这样设计的目的是为了不同环境加载不同的配置文件
